#!/bin/bash

./gradlew clean assembleDebug

for d in $(adb devices | sed 1d | sed 's/device//g'); do adb -s $d shell 'mkdir /sdcard/haps'; adb -s $d push entry/build/outputs/hap/debug/entry-bin-debug-lite-signed.hap /sdcard/haps; done
